<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Gestion des tiers (FACTURATION)</name>
   <tag></tag>
   <elementGuidId>19d920ac-8fab-49e9-95a1-99086b3fa89b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;searchFormList&quot;]/div[2]/div[6]/div[1]/div/div[2]/div[2]/div[2]/a/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Désactivé']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-toggle-off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Désactivé</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchFormList&quot;)/div[@class=&quot;tabBar&quot;]/div[@class=&quot;box-flex-container&quot;]/div[@class=&quot;box-flex-item info-box-module info-box-module-disabled&quot;]/div[@class=&quot;info-box info-box-sm info-box-module&quot;]/div[@class=&quot;info-box-content info-box-text-module&quot;]/div[@class=&quot;valignmiddle inline-block info-box-actions&quot;]/div[@class=&quot;valignmiddle inline-block marginleftonly marginrightonly&quot;]/a[@class=&quot;reposition&quot;]/span[@class=&quot;fas fa-toggle-off&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchFormList']/div[2]/div[4]/div/div/div[2]/div[2]/div[2]/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div[2]/div[2]/a/span</value>
   </webElementXpaths>
</WebElementEntity>
